<ul class="nav-ul">
    <li class="nav-li"><a class="nav-a" href="index.php">Home</a></li>
    <li class="nav-li"><a href="jobs.php" class="nav-a">Description</a></li>
    <li class="nav-li"><a href="apply.php" class="nav-a">Application</a></li>
    <li class="nav-li"><a href="about.php" class="nav-a">About</a></li>
    <li class="nav-li"><a href="manage.php" class="nav-a">Manage</a></li>
    <li style="float:right" class="nav-li"><a href="phpenhancements.php" class="nav-a">Enhancement3</a></li>
    <li style="float:right" class="nav-li"><a href="enhancements2.php" class="nav-a">Enhancement2</a></li>
    <li style="float:right" class="nav-li"><a href="enhancements.php" class="nav-a">Enhancement</a></li>
</ul>