<!DOCTYPE html>
<html lang="en">
<head>
    <?php
        include('header.inc')
    ?>
    <title>PHP Enhancement</title>
</head>
<body>
    <?php
        include('menu.inc')
    ?>

    <div class="enhancement-description">
        <section>
            <h4>Enhancement 1</h4>
            <p>
                The first enhancement I made was to create ascending and descending buttons. When the user clicks these buttons, the table displayed is sorted by the EOInumber. 
                This functionality is implemented in the managesorting.php file. In this file, receive the value of the clicked button using POST (each button has a specific value). 
                Then execute a SELECT query, sort the results based on the EOInumber, and store the sorted results in the sessionStorage.
                In the manage.php file, system check if the session value exists. If it does, retrieve the stored query results from sessionStorage and display them using a foreach loop.
            </p>
            <p> Go to <a href="manage.php">enhancement 1</a></p> 
            <p>Reference</p>
            <p>N/A</p>
        <section>
            <h4>Enhancement 2</h4>
            <p>
                The second enhancement enables users to view reports generated by the system. When the user clicks the "Generate" button, the functionality is triggered in the manageReport.php file. 
                In this file, a SELECT query is executed to retrieve data and present statistics.
                The statistics include the total number of applicants, the number of applicants with specific skills, and the number of applicants for each job position.
            </p>
            <p>Go to <a href="manage.php">enhancement 2</a></p>  
            <p>Reference</p>
            <p>N/A</p>
        </section>
    </div>
    <footer>
        <?php
            include('footer.inc')
        ?>
    </footer>
</body>
</html>
